#!/usr/bin/env bash
# Write frontend/.env.local so Vite proxies match runtime ports.
# Use --refresh to intentionally re-allocate ports.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [ "${1:-}" = "--refresh" ]; then
  "$ROOT/scripts/allocate-ports.sh"
fi
# shellcheck source=ports.sh
source "$ROOT/scripts/ports.sh"

ENV_FILE="$ROOT/frontend/.env.local"
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/sync-dev-env.sh — see config/runtime-ports.json
# Re-run ./scripts/sync-dev-env.sh after restarting backend, then restart npm run dev

AFFINE_API_TARGET=${AFFINE_API_TARGET}
VITE_AFFINE_API_TARGET=${AFFINE_API_TARGET}
VITE_AFFINE_API_BASE=
VITE_UI_PORT=${UI_PORT}
EOF

echo "Wrote $ENV_FILE"
echo "  AFFINE API  → ${AFFINE_API_TARGET}"
echo "  UI          → ${UI_URL}"
echo ""
echo "Restart: cd frontend && npm run dev"
