#!/usr/bin/env bash
# Write frontend/.env.local from config/dev-ports.json (fixed ports).
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=ports.sh
source "$ROOT/scripts/ports.sh"

ENV_FILE="$ROOT/frontend/.env.local"
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/sync-dev-env.sh — ports from config/dev-ports.json
# Re-run after changing dev-ports.json, then restart: npm run dev

AFFINE_API_TARGET=${AFFINE_API_TARGET}
VITE_MOCK_API_TARGET=${MOCK_API_TARGET}
VITE_AFFINE_API_BASE=
EOF

echo "Wrote $ENV_FILE"
echo "  AFFINE API  → ${AFFINE_API_TARGET}"
echo "  Mock API    → ${MOCK_API_TARGET}"
echo "  UI          → ${UI_URL}"
echo ""
echo "Restart: cd frontend && npm run dev"
